apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-upload-manager
  labels:
    app.kubernetes.io/name: node-upload-manager
    app.kubernetes.io/version: v0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-upload-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-upload-manager
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
      - image: waggle/node-upload-manager
        name: node-upload-manager
        resources:
          limits:
            cpu: 500m
            memory: 20Mi
          requests:
            cpu: 250m
            memory: 10Mi
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        - name: remote
          mountPath: /remote
        - name: upload-key
          mountPath: /credentials
          readOnly: true
      volumes:
      - name: uploads
        hostPath:
          path: /uploads
          type: DirectoryOrCreate
      - name: remote
        hostPath:
          path: /remote
          type: DirectoryOrCreate
      - name: upload-key
        secret:
          secretName: node-ssh-key
